"""
vector_db_basics.py
Focus: Understanding Vector Embeddings and Search in DE pipelines.
"""

# Note: In a real environment, you would use 'sentence-transformers' and 'chromadb' or 'pgvector'
# For this tutorial, we will explain the concepts using standard Python.

class MockVectorDB:
    """A simple simulation of how a Vector Database works."""
    def __init__(self):
        self.storage = {} # {id: (metadata, vector)}
        
    def add_record(self, id: int, metadata: dict, vector: list):
        self.storage[id] = (metadata, vector)
        print(f"Stored vector for record {id}: {metadata['text'][:30]}...")

    def cosine_similarity(self, v1, v2):
        """Measures how 'close' two vectors are."""
        # Simplified simulation
        dot_product = sum(a*b for a, b in zip(v1, v2))
        magnitude = (sum(a*a for a in v1)**0.5) * (sum(b*b for b in v2)**0.5)
        return dot_product / magnitude if magnitude > 0 else 0

    def query(self, query_vector: list, top_k: int = 2):
        """Search for the most similar records."""
        results = []
        for id, (meta, vec) in self.storage.items():
            score = self.cosine_similarity(query_vector, vec)
            results.append((score, meta))
        
        # Sort by score descending
        return sorted(results, key=lambda x: x[0], reverse=True)[:top_k]

# --- Execution ---
if __name__ == "__main__":
    vdb = MockVectorDB()

    # Imagine these vectors are generated by an AI model (like OpenAI or HuggingFace)
    vdb.add_record(1, {"text": "How to bake a cake"}, [1.0, 0.1, 0.0])
    vdb.add_record(2, {"text": "Recipe for chocolate brownies"}, [0.9, 0.2, 0.1])
    vdb.add_record(3, {"text": "How to install Linux on a PC"}, [0.0, 0.1, 1.0])

    print("\n--- Querying for 'Cooking Recipes' ---")
    # A vector representing "cooking/food"
    query_vec = [0.95, 0.15, 0.05]
    matches = vdb.query(query_vec)

    for score, meta in matches:
        print(f"Score: {score:.4f} | Result: {meta['text']}")

    # Key Takeaway for DE:
    # A Vector DB is used to store and search unstructured data (text, images) 
    # based on MEANING (vectors) rather than keywords.
    # Your job as a DE is to build the pipeline that converts raw text into these vectors.
